### ISSUE TITLE
api access over http possible? 

### ISSUE THREAD

**Issue by ottobaer** [irrwitzer42/grafana-mailcow#1]
Hi, 

I don't know if this is mailcow specific, but my mailcow installation currently runs on an internal IP that means when I try to use the mailcow exporter it won't connect because of a certificate mismatch. 

    mailcow-exporter     | could not execute API request to `api/v1/get/domain/all`: "Get \"https://10.0.15.1/api/v1/get/domain/all\": x509: cannot validate certificate for 10.0.15.1 because it doesn't contain any IP SANs"

Is there a way to make a connection over http here? 

Thank You,

**Comment by irrwitzer42** [comment]
Hi @ottobaer ,If I understand correctly, you are talking about the connection mailcow-exporter <> mailcow.You will have to ask your question here instead, to get official response: https://github.com/j6s/mailcow-exporterAnyway, I think your approach can easily be optimized:a) put mailcow-exporter in the mailcow-dockerized docker network (mailcow-network) and access the api by calling the api via mailcow’s internal nameb) disable the redirect od http requests to https on your reverse proxy(b)  would mean to connect unencrypted from exporter to mailcow, which is okay locally, but desasterous over the internet.Alternatively you could replace the internal ip address by mailcow’s external fqdn (the correct one).But as I said, maybe better go ask the official devs ;)BR,  JohannesOn 2. Mar 2024, at 10:06, ottobaer ***@***.***> wrote:﻿
Hi,
I don't know if this is mailcow specific, but my mailcow installation currently runs on an internal IP that means when I try to use the mailcow exporter it won't connect because of a certificate mismatch.
mailcow-exporter     | could not execute API request to `api/v1/get/domain/all`: "Get \"https://10.0.15.1/api/v1/get/domain/all\": x509: cannot validate certificate for 10.0.15.1 because it doesn't contain any IP SANs"

Is there a way to make a connection over http here?
Thank You,

**Comment by ottobaer** [comment]
Thanks for the quick answer. 

Yeah I saw after opening this issue that this was linked to the mailcow-exporter - I already asked there :). 

For solution a - how would I  address the mailcow instance with it's internal name ?

As for solution b - I don't even use a reverse proxy, since I'm using a vpn to open a tunnel to my prometheus installation on another server.

**Comment by irrwitzer42** [comment]
Hi @ottobaer ,

> Thanks for the quick answer.

I tried to be quick, but from the phone i wasn’t able to test my suggestions before sending :|

> Yeah I saw after opening this issue that this was linked to the mailcow-exporter - I already asked there :).

Great, maybe this will result in a final and good solution.

> For solution a - how would I address the mailcow instance with it's internal name ?
> As for solution b - I don't even use a reverse proxy, since I'm using a vpn to open a tunnel to my prometheus installation on another server.

As for solution (a) I was thinking it should be possible to not use the IP-address in MAILCOW_EXPORTER_HOST but the frontend;s internal hostname “mailcow-nginx” / “nginx”.
So I tested it right now and it doesn’t work. Maybe because of the inner wokings of the exporter, or the API.

If your Mailcow has a valid certificate for any FQDN you might use the hacky way and add this FQDN with your internal IP-address to the /etc/hosts file of your mailcow-exporter host/container. Then you could use the FQDN in MAILCOW_EXPORTER_HOST and still use the internal IP-address for the API request.

Other than that, my proposed “solutions” weren’t thought through well enough. But your suggestion to add a scheme variable to the exporter sounds good - if the API as accessible via unencrypted HTTP anyway.

I still think it would be best, if the exporter could talk to mailcow within the docker network, not having to take the external route. Then encryption wouldn’t be needed when run locally within the same docker stack and with your VPN transport between prometheus and mailcow you would be good to go. In my case I use the reverse proxy and SSL to secure this part of the communication.


Good luck!
